#!/usr/bin/env bash
#
# bootstrap install things

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

generateSSHKeyForGithub() {
  source $DOTFILES_ROOT/git/ssh.sh
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    user ' - Do you want to generate a new ssh key to github? (y/N)'
    read -e generate_ssh_key

    if [[ $generate_ssh_key =~ ^[Yy]$ ]]
    then
        generateSSHKeyForGithub
    fi

    success 'Git configuration finished successfully'
  fi
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'Installing dotfiles...'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_zsh() {

  if test ! $(which omz); then
    info "Installing OhMyZSH..."

    rm -rf $HOME/.oh-my-zsh/
    curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh

    echo 'Installing ZSH Autosuggestions...'
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

    echo 'Installing ZSH syntax highlighting...'
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    success "OhMyZSH installed!"
  fi
}

function generate_gpg_key() {
  info "Generating a new GPG key to GitHub..."

# Generating a new GPG key
# https://docs.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key
gpg --full-generate-key

#Use the gpg --list-secret-keys --keyid-format LONG command to list GPG keys for
# which you have both a public and private key. A private key is required for signing commits or tags.
gpg --list-secret-keys --keyid-format LONG

user " - From the list of GPG keys, copy the GPG key ID you'd like to use"
read -e selected_gpg

# Prints the GPG key ID, in ASCII armor format
gpg --armor --export $selected_gpg

info "Copy your GPG key, beginning with -----BEGIN PGP PUBLIC KEY BLOCK----- and ending with -----END PGP PUBLIC KEY BLOCK-----."

git config --global user.signingkey $selected_gpg
}

setup_gitconfig

user ' - Do you want to install OhMyZSH? (y/N)'
read -e want_to_install_zsh

if [[ $want_to_install_zsh =~ ^[Yy]$ ]]
then
    install_zsh
fi

install_dotfiles

user ' - Do you want to generate a GPG key for github? (y/N)'
read -e want_to_generate_gpg_key

if [[ $want_to_generate_gpg_key =~ ^[Yy]$ ]]
then
    generate_gpg_key
fi

success "Installation finished successfully!"