#!/usr/bin/env bash
#
# Run all dotfiles installers

set -e

cd "$(dirname $0)"/..

echo $(pwd)

read -p " - Do you want to install Brew dependencies? [y/n] " -r

if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "> Brew bundle"
    brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done